version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: test-residencial-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test-residencial
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gestcom-network

networks:
  gestcom-network:

volumes:
  postgres-data: